### ISSUE TITLE
DSi doesn't connect to WPA hotspot

### ISSUE THREAD

**Issue by Tcm0** [shinyquagsire23/dsiwifi#1]
I tried the test application and the DSi doesn't get an IP, it loops the following commands:
tcp_close: invalid pcbtcp_new failed...
netif is not up, old style port?

I can use the DSi browser just fine. The router is set to WPA+WPA2.

**Comment by Epicpkmn11** [comment]
if you've got any other routers or hotspot devices, try those. it's very picky about routers at the moment and just refuses to connect sometimes for whatever reason

I think it might've also varied by console a bit which ones it liked, but that might be fixed by the latest version, I don't remember exactly

**Comment by Tcm0** [comment]
I switched my router to "WPA2 (CCMP)" and now it works.
Also, it doesn't work if launched from the camera app via memory pit
